# Dependencies
markdown:         kramdown
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Yachting weekend
tagline:          Give your weekend some sailing
url:              http://yachtingweekend.com
baseurl:          /
author:
  name:           Taras Kalapun
  url:            https://twitter.com/xslim
  email:          t@kalapun.com

title_tag_text: Solo, a Jekyll Theme
h1_tag_text: Solo

exclude: ["Procfile", "Gruntfile.js", "package.json", "CNAME", "node_modules"]
